// Generated by ExcaliburJS Tilemap warehousegraph Editor
// Tilemap: warehouseLower.png | Tile Size: 16x16
// Total Nodes: 41 | Total Edges: 54

import { Graph, vec } from "excalibur";

const warehousegraph = new Graph();

// Register Nodes
const node_0 = warehousegraph.addNode({}, vec(24, 88));
const node_1 = warehousegraph.addNode({}, vec(40, 88));
const node_2 = warehousegraph.addNode({}, vec(56, 88));
const node_3 = warehousegraph.addNode({}, vec(72, 88));
const node_4 = warehousegraph.addNode({}, vec(88, 88));
const node_5 = warehousegraph.addNode({}, vec(104, 88));
const node_6 = warehousegraph.addNode({}, vec(120, 88));
const node_7 = warehousegraph.addNode({}, vec(120, 104));
const node_8 = warehousegraph.addNode({}, vec(136, 104));
const node_9 = warehousegraph.addNode({}, vec(152, 104));
const node_10 = warehousegraph.addNode({}, vec(120, 120));
const node_11 = warehousegraph.addNode({}, vec(136, 120));
const node_12 = warehousegraph.addNode({}, vec(152, 120));
const node_13 = warehousegraph.addNode({}, vec(24, 136));
const node_14 = warehousegraph.addNode({}, vec(40, 136));
const node_15 = warehousegraph.addNode({}, vec(56, 136));
const node_16 = warehousegraph.addNode({}, vec(72, 136));
const node_17 = warehousegraph.addNode({}, vec(88, 136));
const node_18 = warehousegraph.addNode({}, vec(104, 136));
const node_19 = warehousegraph.addNode({}, vec(120, 136));
const node_20 = warehousegraph.addNode({}, vec(136, 136));
const node_21 = warehousegraph.addNode({}, vec(152, 136));
const node_22 = warehousegraph.addNode({}, vec(88, 152));
const node_23 = warehousegraph.addNode({}, vec(104, 152));
const node_24 = warehousegraph.addNode({}, vec(120, 152));
const node_25 = warehousegraph.addNode({}, vec(136, 152));
const node_26 = warehousegraph.addNode({}, vec(152, 152));
const node_27 = warehousegraph.addNode({}, vec(88, 168));
const node_28 = warehousegraph.addNode({}, vec(104, 168));
const node_29 = warehousegraph.addNode({}, vec(120, 168));
const node_30 = warehousegraph.addNode({}, vec(136, 168));
const node_31 = warehousegraph.addNode({}, vec(24, 184));
const node_32 = warehousegraph.addNode({}, vec(40, 184));
const node_33 = warehousegraph.addNode({}, vec(56, 184));
const node_34 = warehousegraph.addNode({}, vec(72, 184));
const node_35 = warehousegraph.addNode({}, vec(88, 184));
const node_36 = warehousegraph.addNode({}, vec(104, 184));
const node_37 = warehousegraph.addNode({}, vec(120, 184));
const node_38 = warehousegraph.addNode({}, vec(136, 184));
const node_39 = warehousegraph.addNode({}, vec(152, 184));
const node_40 = warehousegraph.addNode({}, vec(88, 200));

// Connect Edges
warehousegraph.addEdge(node_1, node_0, { weight: 16 });
warehousegraph.addEdge(node_2, node_1, { weight: 16 });
warehousegraph.addEdge(node_3, node_2, { weight: 16 });
warehousegraph.addEdge(node_4, node_3, { weight: 16 });
warehousegraph.addEdge(node_5, node_4, { weight: 16 });
warehousegraph.addEdge(node_6, node_5, { weight: 16 });
warehousegraph.addEdge(node_7, node_6, { weight: 16 });
warehousegraph.addEdge(node_10, node_7, { weight: 16 });
warehousegraph.addEdge(node_19, node_10, { weight: 16 });
warehousegraph.addEdge(node_24, node_19, { weight: 16 });
warehousegraph.addEdge(node_29, node_24, { weight: 16 });
warehousegraph.addEdge(node_37, node_29, { weight: 16 });
warehousegraph.addEdge(node_8, node_7, { weight: 16 });
warehousegraph.addEdge(node_9, node_8, { weight: 16 });
warehousegraph.addEdge(node_11, node_10, { weight: 16 });
warehousegraph.addEdge(node_11, node_8, { weight: 16 });
warehousegraph.addEdge(node_12, node_9, { weight: 16 });
warehousegraph.addEdge(node_12, node_11, { weight: 16 });
warehousegraph.addEdge(node_20, node_19, { weight: 16 });
warehousegraph.addEdge(node_20, node_11, { weight: 16 });
warehousegraph.addEdge(node_21, node_12, { weight: 16 });
warehousegraph.addEdge(node_21, node_20, { weight: 16 });
warehousegraph.addEdge(node_25, node_24, { weight: 16 });
warehousegraph.addEdge(node_25, node_20, { weight: 16 });
warehousegraph.addEdge(node_26, node_21, { weight: 16 });
warehousegraph.addEdge(node_26, node_25, { weight: 16 });
warehousegraph.addEdge(node_30, node_29, { weight: 16 });
warehousegraph.addEdge(node_30, node_25, { weight: 16 });
warehousegraph.addEdge(node_38, node_37, { weight: 16 });
warehousegraph.addEdge(node_38, node_30, { weight: 16 });
warehousegraph.addEdge(node_39, node_38, { weight: 16 });
warehousegraph.addEdge(node_32, node_31, { weight: 16 });
warehousegraph.addEdge(node_33, node_32, { weight: 16 });
warehousegraph.addEdge(node_34, node_33, { weight: 16 });
warehousegraph.addEdge(node_35, node_34, { weight: 16 });
warehousegraph.addEdge(node_36, node_37, { weight: 16 });
warehousegraph.addEdge(node_36, node_35, { weight: 16 });
warehousegraph.addEdge(node_40, node_35, { weight: 16 });
warehousegraph.addEdge(node_14, node_13, { weight: 16 });
warehousegraph.addEdge(node_15, node_14, { weight: 16 });
warehousegraph.addEdge(node_16, node_15, { weight: 16 });
warehousegraph.addEdge(node_17, node_16, { weight: 16 });
warehousegraph.addEdge(node_18, node_19, { weight: 16 });
warehousegraph.addEdge(node_18, node_17, { weight: 16 });
warehousegraph.addEdge(node_22, node_17, { weight: 16 });
warehousegraph.addEdge(node_23, node_24, { weight: 16 });
warehousegraph.addEdge(node_23, node_18, { weight: 16 });
warehousegraph.addEdge(node_23, node_22, { weight: 16 });
warehousegraph.addEdge(node_27, node_35, { weight: 16 });
warehousegraph.addEdge(node_27, node_22, { weight: 16 });
warehousegraph.addEdge(node_28, node_29, { weight: 16 });
warehousegraph.addEdge(node_28, node_36, { weight: 16 });
warehousegraph.addEdge(node_28, node_23, { weight: 16 });
warehousegraph.addEdge(node_28, node_27, { weight: 16 });

export { warehousegraph };
